import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-materiademo',
  templateUrl: './materiademo.component.html',
  styleUrls: ['./materiademo.component.css']
})
export class MateriademoComponent{
  data = [
    {Name:'Turkey', Price:'500k', Pic:"assets/Amazing-Ship-HD-Desktop-Wallpaper.jpg"},
    {Name:'Qustuntunia', Price:'1.25 million', Pic:"assets/Antranias_A Tiny House With Ivy Flowers_YkViSWo.jpg"},
    {Name:'Japan', Price:'900k', Pic:"assets/awesome_japan_city_tokyo_wallpaper_hd_4.jpg"},
    {Name:'Water City', Price:'1.1 million', Pic:"assets/beautiful-water-city.jpg"},
    {Name:'Dubai', Price:'860k', Pic:"assets/city-highways-night.jpg"},
    {Name:'NYC', Price:'1.5 million', Pic:"assets/city-lights-hd-wallpaper-15.jpg"},
    {Name:'Las Vegas', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-1.jpg"},
    {Name:'Chicago', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-7.jpg"},
    {Name:'India', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-5.jpg"},
    {Name:'Maldives', Price:'1.0 million', Pic:"assets/Sailboat-HD-Desktop-Wallpaper.jpg"},
    {Name:'Turkey', Price:'500k', Pic:"assets/Amazing-Ship-HD-Desktop-Wallpaper.jpg"},
    {Name:'Qustuntunia', Price:'1.25 million', Pic:"assets/Antranias_A Tiny House With Ivy Flowers_YkViSWo.jpg"},
    {Name:'Japan', Price:'900k', Pic:"assets/awesome_japan_city_tokyo_wallpaper_hd_4.jpg"},
    {Name:'Water City', Price:'1.1 million', Pic:"assets/beautiful-water-city.jpg"},
    {Name:'Dubai', Price:'860k', Pic:"assets/city-highways-night.jpg"},
    {Name:'NYC', Price:'1.5 million', Pic:"assets/city-lights-hd-wallpaper-15.jpg"},
    {Name:'Las Vegas', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-1.jpg"},
    {Name:'Chicago', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-7.jpg"},
    {Name:'India', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-5.jpg"},
    {Name:'Maldives', Price:'1.0 million', Pic:"assets/Sailboat-HD-Desktop-Wallpaper.jpg"},
    {Name:'Turkey', Price:'500k', Pic:"assets/Amazing-Ship-HD-Desktop-Wallpaper.jpg"},
    {Name:'Qustuntunia', Price:'1.25 million', Pic:"assets/Antranias_A Tiny House With Ivy Flowers_YkViSWo.jpg"},
    {Name:'Japan', Price:'900k', Pic:"assets/awesome_japan_city_tokyo_wallpaper_hd_4.jpg"},
    {Name:'Water City', Price:'1.1 million', Pic:"assets/beautiful-water-city.jpg"},
    {Name:'Dubai', Price:'860k', Pic:"assets/city-highways-night.jpg"},
    {Name:'NYC', Price:'1.5 million', Pic:"assets/city-lights-hd-wallpaper-15.jpg"},
    {Name:'Las Vegas', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-1.jpg"},
    {Name:'Chicago', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-7.jpg"},
    {Name:'India', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-5.jpg"},
    {Name:'Maldives', Price:'1.0 million', Pic:"assets/Sailboat-HD-Desktop-Wallpaper.jpg"},
    {Name:'Turkey', Price:'500k', Pic:"assets/Amazing-Ship-HD-Desktop-Wallpaper.jpg"},
    {Name:'Qustuntunia', Price:'1.25 million', Pic:"assets/Antranias_A Tiny House With Ivy Flowers_YkViSWo.jpg"},
    {Name:'Japan', Price:'900k', Pic:"assets/awesome_japan_city_tokyo_wallpaper_hd_4.jpg"},
    {Name:'Water City', Price:'1.1 million', Pic:"assets/beautiful-water-city.jpg"},
    {Name:'Dubai', Price:'860k', Pic:"assets/city-highways-night.jpg"},
    {Name:'NYC', Price:'1.5 million', Pic:"assets/city-lights-hd-wallpaper-15.jpg"},
    {Name:'Las Vegas', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-1.jpg"},
    {Name:'Chicago', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-7.jpg"},
    {Name:'India', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-5.jpg"},
    {Name:'Maldives', Price:'1.0 million', Pic:"assets/Sailboat-HD-Desktop-Wallpaper.jpg"},
    {Name:'Turkey', Price:'500k', Pic:"assets/Amazing-Ship-HD-Desktop-Wallpaper.jpg"},
    {Name:'Qustuntunia', Price:'1.25 million', Pic:"assets/Antranias_A Tiny House With Ivy Flowers_YkViSWo.jpg"},
    {Name:'Japan', Price:'900k', Pic:"assets/awesome_japan_city_tokyo_wallpaper_hd_4.jpg"},
    {Name:'Water City', Price:'1.1 million', Pic:"assets/beautiful-water-city.jpg"},
    {Name:'Dubai', Price:'860k', Pic:"assets/city-highways-night.jpg"},
    {Name:'NYC', Price:'1.5 million', Pic:"assets/city-lights-hd-wallpaper-15.jpg"},
    {Name:'Las Vegas', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-1.jpg"},
    {Name:'Chicago', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-7.jpg"},
    {Name:'India', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-5.jpg"},
    {Name:'Maldives', Price:'1.0 million', Pic:"assets/Sailboat-HD-Desktop-Wallpaper.jpg"},
    {Name:'Turkey', Price:'500k', Pic:"assets/Amazing-Ship-HD-Desktop-Wallpaper.jpg"},
    {Name:'Qustuntunia', Price:'1.25 million', Pic:"assets/Antranias_A Tiny House With Ivy Flowers_YkViSWo.jpg"},
    {Name:'Japan', Price:'900k', Pic:"assets/awesome_japan_city_tokyo_wallpaper_hd_4.jpg"},
    {Name:'Water City', Price:'1.1 million', Pic:"assets/beautiful-water-city.jpg"},
    {Name:'Dubai', Price:'860k', Pic:"assets/city-highways-night.jpg"},
    {Name:'NYC', Price:'1.5 million', Pic:"assets/city-lights-hd-wallpaper-15.jpg"},
    {Name:'Las Vegas', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-1.jpg"},
    {Name:'Chicago', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-7.jpg"},
    {Name:'India', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-5.jpg"},
    {Name:'Maldives', Price:'1.0 million', Pic:"assets/Sailboat-HD-Desktop-Wallpaper.jpg"},
    {Name:'Turkey', Price:'500k', Pic:"assets/Amazing-Ship-HD-Desktop-Wallpaper.jpg"},
    {Name:'Qustuntunia', Price:'1.25 million', Pic:"assets/Antranias_A Tiny House With Ivy Flowers_YkViSWo.jpg"},
    {Name:'Japan', Price:'900k', Pic:"assets/awesome_japan_city_tokyo_wallpaper_hd_4.jpg"},
    {Name:'Water City', Price:'1.1 million', Pic:"assets/beautiful-water-city.jpg"},
    {Name:'Dubai', Price:'860k', Pic:"assets/city-highways-night.jpg"},
    {Name:'NYC', Price:'1.5 million', Pic:"assets/city-lights-hd-wallpaper-15.jpg"},
    {Name:'Las Vegas', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-1.jpg"},
    {Name:'Chicago', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-7.jpg"},
    {Name:'India', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-5.jpg"},
    {Name:'Maldives', Price:'1.0 million', Pic:"assets/Sailboat-HD-Desktop-Wallpaper.jpg"},
    {Name:'Turkey', Price:'500k', Pic:"assets/Amazing-Ship-HD-Desktop-Wallpaper.jpg"},
    {Name:'Qustuntunia', Price:'1.25 million', Pic:"assets/Antranias_A Tiny House With Ivy Flowers_YkViSWo.jpg"},
    {Name:'Japan', Price:'900k', Pic:"assets/awesome_japan_city_tokyo_wallpaper_hd_4.jpg"},
    {Name:'Water City', Price:'1.1 million', Pic:"assets/beautiful-water-city.jpg"},
    {Name:'Dubai', Price:'860k', Pic:"assets/city-highways-night.jpg"},
    {Name:'NYC', Price:'1.5 million', Pic:"assets/city-lights-hd-wallpaper-15.jpg"},
    {Name:'Las Vegas', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-1.jpg"},
    {Name:'Chicago', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-7.jpg"},
    {Name:'India', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-5.jpg"},
    {Name:'Maldives', Price:'1.0 million', Pic:"assets/Sailboat-HD-Desktop-Wallpaper.jpg"},
    {Name:'Turkey', Price:'500k', Pic:"assets/Amazing-Ship-HD-Desktop-Wallpaper.jpg"},
    {Name:'Qustuntunia', Price:'1.25 million', Pic:"assets/Antranias_A Tiny House With Ivy Flowers_YkViSWo.jpg"},
    {Name:'Japan', Price:'900k', Pic:"assets/awesome_japan_city_tokyo_wallpaper_hd_4.jpg"},
    {Name:'Water City', Price:'1.1 million', Pic:"assets/beautiful-water-city.jpg"},
    {Name:'Dubai', Price:'860k', Pic:"assets/city-highways-night.jpg"},
    {Name:'NYC', Price:'1.5 million', Pic:"assets/city-lights-hd-wallpaper-15.jpg"},
    {Name:'Las Vegas', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-1.jpg"},
    {Name:'Chicago', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-7.jpg"},
    {Name:'India', Price:'1.0 million', Pic:"assets/New-York-City-HD-Wallpapers-1080p-5.jpg"},
    {Name:'Maldives', Price:'1.0 million', Pic:"assets/Sailboat-HD-Desktop-Wallpaper.jpg"},
  ];

}
